# version: '3.8'

# services:
#   db:
#     image: postgres:16
#     container_name: postgres-db
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: api_cervical
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

# networks:
#   dev_network:
#     driver: bridge

# #docker-compose -p cervical up -d